@echo off
echo Starting Fruit Compute Engine Server...
echo.
echo Starting RMI Registry on port 1099...
start "RMI Registry" rmiregistry 1099
echo Waiting for RMI Registry to start...
timeout /t 3 /nobreak > nul
echo.
echo Starting Fruit Compute Engine...
java -cp target\classes -Djava.rmi.server.hostname=10.50.48.187 server.FruitComputeEngine
pause
